version: '3'

services:
  laravel:
    container_name: laravel
    build:
      context: .
      dockerfile: ./back/Dockerfile
    ports:
    - "8080:80"
    volumes:
    - ./back:/usr/share/nginx
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    ports:
    - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
