<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Services\UserService;
use Illuminate\Http\Request;

class UserController extends AbstractController
{
    protected $service;
    protected $requestValidate = UserRequest::class;

    /**
     * @OA\Get(
     * path="/api/user",
     * summary="Listagem de Usuários",
     * description="Listagem de usuários do sistema",
     * operationId="user/get",
     * tags={"user"},
     * security={ {"bearer": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiZWNhZmNiOWY3ZDc2MGUxMmMwNjhkNmE4YjE5MGNlOGE0MjYzYmFlMjUzZDUzY2VhZjM0Nzk5YmViODc0NDNmZTQ1MTIwNzJiMWRkYmRmZGYiLCJpYXQiOjE2MDM2MDU1NDUsIm5iZiI6MTYwMzYwNTU0NSwiZXhwIjoxNjAzNjkxOTQ1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.vLS4wGT7TS4b_CySPN_QQ_JyZXk2vWl8j3ksAoxes5lLwaveKF3t63lXl9AaGACp0x9HUMlHffkXLpL061Q70JzAdKd3MXhbx_4xe2H3YLabSnNqGyAjKcm_rvXcj-LQsWDcxvoRf-aWHEKiPEfSNr-7UwBZ_82UDaVVYBfH_MVbqgdM4j3DAQuDpv3OAJceMcLcXMafr2A4O65uXbosc3rlZPTFmmzQX58xY3PAn0lUoSxlh36rXMEnJY47ul0A60_knZ7WYfuqFA7Z0CnKQCpFaM_9bIgKEtRwYyYj09hLAWm7n6WBllyos10OSxsIfUUsOCb_LJFb5jDbZ2OkjO0B5SEjqV2ojRTeCn4e9mnlCDd33KeRFkUv9GNyXELNp0mnfpDJH-fFyzpsQvrrTvXDs7cfp42ColexuZcsggS9nA3PLYJunbEFo9vI9h3ECVu8zNRcGC8oTNuKdzf0PJp-YUp7j_Xu819mkaBkRAiMh-M7NFPM1JzNZ0gw3vwP-6ptacMww_yiMFCe_zzlk6iBWpIjavUhGgAeHJAdXs69AW1caAQBN8c5_ebiuJ1SUfu1dmeH85zOr1TUfZV90harEVnTh0J66HxqWnKZJEBXY4eCYinRHn8pgE6adCUjkTq_Rdik6bX5wnfNoYVmzzJJ8QX2EhErfU4fANWz6vU" }},
     *  @OA\Response(
     *      response=200,
     *      description="Success",
     *  )
     * )
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * UserController constructor.
     * @param UserService $userService
     */
    public function __construct(UserService $userService)
    {
        $this->service = $userService;
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function show(int $id)
    {
        return $this->ok($this->service->fetchUser($id));
    }

    /**
     * Cadastro externo de usuário
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function cadastrar(Request $request)
    {
        try {
            $user = $this->service->cadastrar($request->all());
            return $this->success('Cadastro efetuado com sucesso', ['user' => $user]);
        } catch (\Exception $e) {
            return $this->error($e->getMessage());
        }
    }

    /**
     * @param Request $request
     */
    public function recuperarSenha(Request $request)
    {

    }
}
